# The URL the site will be built for
base_url = "https://ss3d.space/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
external_links_target_blank = true

[extra]
# Put all your custom variables here

github_url = "https://github.com/RE-SS3D"
github_game_url = "https://github.com/RE-SS3D/SS3D"
github_artwork_url = "https://raw.githubusercontent.com/RE-SS3D/SS3D-Art/main/Artwork"
discord_url = "https://discord.gg/3ny9tdH"
twitter_url = "https://twitter.com/SpaceStation3D"
youtube_url = "https://www.youtube.com/@spacestation3d"
patreon_url = "https://www.patreon.com/ss3d"
paypal_url = "https://www.paypal.me/SpaceStation3D"
subscribestar_url = "https://www.subscribestar.com/space-station-3d"
gitbook_url = "https://ss3d.gitbook.io"

latest_release = "0.0.7.3"

[[extra.social_icons]]
title = "GitHub"
name = "github"
url = "https://github.com/RE-SS3D"

[[extra.social_icons]]
title = "Patreon"
name = "patreon"
url = "https://www.patreon.com/ss3d"

[[extra.social_icons]]
title = "Discord"
name = "discord"
url = "https://discord.gg/3ny9tdH"

[[extra.social_icons]]
title = "YouTube"
name = "youtube"
url = "https://www.youtube.com/@spacestation3d"

[[extra.social_icons]]
title = "Reddit"
name = "reddit"
url = "https://reddit.com/r/RESS3D"

[[extra.social_icons]]
title = "Twitter"
name = "twitter"
url = "https://twitter.com/SpaceStation3D"

[extra.images.post]
default_size = 580
image_sizes = [290, 580]
sizes = "(max-width: 624px) 100vw, 580px"

[extra.images.split]
default_size = 290
image_sizes = [290]
sizes = "(max-width: 624px) 50vw, 290px"
